# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /phoneShop

spring:
  application:
    name: web-sales-backend
  
  # Database Configuration
  datasource:
    url:  "jdbc:mysql://mysql-2646241a-myloc203-df70.e.aivencloud.com:24714/phoneShop"
    username: avnadmin
    password: AVNS_HNcbA_yh7QK4UPUikiH
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      repositories:
        enabled: false

  # JPA Configuration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # H2 Database (for development/testing)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # AI
  ai:
    openai:
      api-key: AIzaSyBrTipp-3SITKxs3t7cN3eP2crvOG9edfs
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

# JWT Configuration
jwt:
  signerKey: "4fenEIft8k/ii3gdEbIEiNzAz8A6SHw4gmq98FuMVbYffeCwLUFwKkcx8g7mZqWV0ZtPMFzEw1yKfF3pHoREXOznR2a/4PCFQWQxUTH3Zrb1QT1sBqenm3/UdM1PWAFS"
  expiration: 8640000000
  refreshable-duration: 360000

# File Upload Configuration
file:
  upload-dir: uploads/
  max-file-size: 10MB
  max-request-size: 10MB

# Logging Configuration
logging:
  level:
    com.websales: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/websales.log

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Custom Application Properties
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
  admin:
    default-email: admin@websales.com
    default-password: admin123


cloudinary:
  cloud:
    name: dpf4ph1qu
  api:
    key: 756234473817482
    secret: T5qQXodnthydHuSyQYrF-xk98Eo
#  T5qQXodnthydHuSyQYrF-xk98Eo


speedsms:
  access_token: "keZn3M1sLGxNoLXAokT814YRisuw0L47"

# PayOS Configuration
payos:
  client-id: ${PAYOS_CLIENT_ID:1e486ec0-9fac-4d03-9f38-c30f9987e1f0}
  api-key: ${PAYOS_API_KEY:0993fd87-b82f-4d17-8ebc-e47deb600a9a}
  checksum-key: ${PAYOS_CHECKSUM_KEY:882ff1d4a906a720c4c4ac414a2def108b0eea3f2735950dc96e80315502a8c7}
  log-level: ${PAYOS_LOG_LEVEL:INFO} # DEBUG | INFO | NONE


